ALTER TABLE profiles ADD COLUMN IF NOT EXISTS live_earnings   NUMERIC(12,2) DEFAULT NULL;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS live_cashes     INTEGER       DEFAULT NULL;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS live_wins       INTEGER       DEFAULT NULL;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS top_10_results  INTEGER       DEFAULT NULL;
